<?

/**
 * Implements hook_block_info().
 */
function viewer_count_init() {
  drupal_add_js(drupal_get_path('module', 'viewer_count') .'/viewer_count.js', array('scope' => 'footer'));
  drupal_add_css(drupal_get_path('module', 'viewer_count') .'/viewer_count.css'); 
}
function viewer_count_block_info() {
  $blocks = array();
  $blocks['popup'] = array(
    'info' => t('Viewer Count'),
  );
 
  return $blocks;
}
/**
 * Implements hook_block_configure().
 */
function viewer_count_block_configure($delta='') {
  $form = array();
 
  switch($delta) {
    case 'popup' :
      // Text field form element
      $form['text_body'] = array(
        '#type' => 'text_format',
		 '#format' => 'plain_text',
		 '#maxlength' => '200',
		 '#rows' => '1',
        '#title' => t('Enter your Header Text here'),
        '#default_value' => variable_get('text_variable', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function viewer_count_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'popup' :
      // Saving the WYSIWYG text      
      variable_set('text_variable', $edit['text_body']['value']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function viewer_count_block_view($delta='') {
  $block = array();


 $text = variable_get('text_variable', '');
  switch($delta) {
    case 'popup' :
      $block['content'] = "<div id='VC'>
<div id='VC-body'>
<div class='header'>
<h2>".$text."</h2>
</div>

<div class='vc-buttons'>
<p>
<button id='vc1' class='vc_option button blue spaced'>Just Me</button>
<button id='vc2' class='vc_option button blue spaced'>2</button>
<button id='vc3' class='vc_option button blue spaced'>3</button>
<button id='vc4' class='vc_option button blue spaced'>4</button>
<button id='vc5' class='vc_option button blue spaced'>5</button>
<button id='vc6' class='vc_option button blue spaced'>6+</button></p>
</div>

<footer><a id='vc0' class='vc_skip'>Click Here to Skip</a></footer>
</div>
</div>

<div id='overlay-VC'>&nbsp;</div>";
      break;
  }
 
  return $block;
}
 
/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function popup_view() {
  $block = array();
 
  // Capture WYSIWYG text from the variable
  
 
  // Block output in HTML with div wrapper
  $block = array(
    'image' => array(
      '#prefix' => '<div class="class_name">',
      '#type' => 'markup',
      '#markup' => $image,
    ),
    'message' => array(
      '#type' => 'markup',
      '#markup' => $text,
      '#suffix' => '</div>',
    ),
  );
 
  return $block;
}